# Generated by Django 5.2 on 2025-05-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(db_column='IS_SUPERUSER', default=False)),
                ('email', models.EmailField(db_column='EMAIL_ID', max_length=254, unique=True)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=15)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=15, null=True)),
                ('password', models.TextField(blank=True, db_column='PASSWORD', null=True)),
                ('phone_number', models.CharField(blank=True, db_column='PHONE_NUMBER', max_length=15, null=True)),
                ('business_name', models.CharField(blank=True, db_column='BUSINESS_NAME', max_length=100, null=True)),
                ('is_available_today', models.BooleanField(db_column='IS_AVAILABLE_TODAY', default=False)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('last_login', models.DateTimeField(blank=True, db_column='LAST_LOGIN', null=True)),
                ('user_type', models.PositiveIntegerField(blank=True, db_column='USER_TYPE', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CREATED_ON')),
                ('created_by', models.PositiveIntegerField(blank=True, db_column='CREATED_BY', null=True)),
                ('modified_on', models.DateTimeField(db_column='MODIFIED_ON', null=True)),
                ('modified_by', models.PositiveIntegerField(blank=True, db_column='MODIFIED_BY', null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'USER',
                'ordering': ['first_name'],
            },
        ),
    ]
