# Generated by Django 5.2 on 2025-05-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_user_gender_userprofile_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='closing_time',
            field=models.TimeField(blank=True, db_column='CLOSING_TIME', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='opening_time',
            field=models.TimeField(blank=True, db_column='OPENING_TIME', null=True),
        ),
    ]
