# Generated by Django 5.2 on 2025-09-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0004_vendorshopimage"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="USERS",
        ),
    ]
