# Generated by Django 5.2 on 2025-05-19 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, db_column='GENDER', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('address', models.TextField(blank=True, db_column='ADDRESS', null=True)),
                ('shop_address', models.TextField(blank=True, db_column='SHOP_ADDRESS', null=True)),
                ('shop_description', models.TextField(blank=True, db_column='SHOP_DESCRIPTION', null=True)),
                ('profile_picture', models.CharField(blank=True, db_column='PROFILE_PICTURE', max_length=500, null=True)),
                ('user', models.OneToOneField(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'USER_PROFILE',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, db_column='DATE')),
                ('status', models.PositiveIntegerField(db_column='ATTENDANCE_STATUS')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='TIMESTAMP')),
                ('vendor', models.ForeignKey(db_column='VENDOR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'ATTENDANCE',
                'unique_together': {('vendor', 'date', 'status')},
            },
        ),
    ]
