# Generated by Django 5.2 on 2025-05-19 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_userprofile_closing_time_userprofile_opening_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('shop_image', models.CharField(blank=True, db_column='SHOP_IMAGE', max_length=500, null=True)),
                ('vendor', models.ForeignKey(db_column='VENDOR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='shop_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Shop Image',
                'verbose_name_plural': 'Vendor Shop Images',
                'db_table': 'VENDOR_SHOP_IMAGE',
            },
        ),
    ]
